# Vancouver Cycling Data

### Imports

In [1]:
%pip install pandas
%pip install openpyxl
%pip install matplotlib

import sys
import os
import datetime
import pandas as pd
import urllib.request

%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (20.0, 10.0)

Collecting pandas

  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)

Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)

Requirement already satisfied: python-dateutil>=2.8.2 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)

Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)

Requirement already satisfied: tzdata>=2022.7 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/12.4 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 8.4/12.4 MB 43.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 30.5 MB/s  0:00:00

Downloading numpy-2.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/16.6 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 13.9/16.6 MB 69.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 16.5/16.6 MB 65.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 38.0 MB/s  0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)

Installing collected packages: pytz, numpy, pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [pytz]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [numpy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]
Successfully installed numpy-2.3.5 pandas-2.3.3 pytz-2025.2

Note: you may need to restart the kernel to use updated packages.

Collecting openpyxl

  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)

Collecting et-xmlfile (from openpyxl)

  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)

Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)

Installing collected packages: et-xmlfile, openpyxl

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 [openpyxl]

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 [openpyxl]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

Note: you may need to restart the kernel to use updated packages.

Collecting matplotlib

  Downloading matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)

Collecting contourpy>=1.0.1 (from matplotlib)

  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)

  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)

Collecting fonttools>=4.22.0 (from matplotlib)

  Downloading fonttools-4.60.1-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (112 kB)

Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)

Requirement already satisfied: numpy>=1.23 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from matplotlib) (25.0)

Collecting pillow>=8 (from matplotlib)

  Downloading pillow-12.0.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)

Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/jules/.pyenv/versions/3.12.12/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

Downloading matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/8.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 39.0 MB/s  0:00:00

Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)

Downloading fonttools-4.60.1-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.9 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 47.7 MB/s  0:00:00

Downloading kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 93.7 MB/s  0:00:00
Downloading pillow-12.0.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/7.0 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 32.2 MB/s  0:00:00

Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)

Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [pillow]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [pillow]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [pillow]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [pillow]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [pillow]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [fonttools]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [matplotlib]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.60.1 kiwisolver-1.4.9 matplotlib-3.10.7 pillow-12.0.0 pyparsing-3.2.5

Note: you may need to restart the kernel to use updated packages.

### Fetching Data

In [2]:
# Variables 
# url = "https://vancouver.ca/files/cov/Bike-lane-stats-by-month.pdf"
url = "https://vancouver.ca/files/cov/bike-volume-2021-2024.xlsx"
data_path = "data"
now = pd.to_datetime('now').date()
file_name = 'bike-volume-2021-2024_{}.xlsx'.format(now)

# Path
if not os.path.exists(data_path):
    os.makedirs(data_path)
resolved_file_path = os.path.join(data_path, file_name)

# Download 
print("### Downloading " + url + " and saving at " + resolved_file_path)
if not os.path.exists(resolved_file_path):
    urllib.request.urlretrieve(url, resolved_file_path)

### Downloading https://vancouver.ca/files/cov/bike-volume-2021-2024.xlsx and saving at data/bike-volume-2021-2024_2025-11-25.xlsx

### Loading Data

In [3]:
# Which worksheet to load: choose between 'Documentation' and the data sheet
# Keep as a single variable so it's easy to change later
sheet_name = 'City of Vancouver Bike Data'

# Read the worksheet directly. 
# Use header=0 to properly parse column names
df = pd.read_excel(resolved_file_path, sheet_name=sheet_name, header=0)

In [4]:
df.head()

,Location,Direction,CorrectionFactor,PercentPassing20%,PercentPassing10%,date,Volume
0,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Westbound,1.106145,0.7,0.6,2021-01-01,91.810056
1,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Eastbound,1.106145,0.7,0.6,2021-01-01,3.318436
2,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Westbound,1.106145,0.7,0.6,2021-01-02,57.519553
3,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Eastbound,1.106145,0.7,0.6,2021-01-02,4.424581
4,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Westbound,1.106145,0.7,0.6,2021-01-03,315.251397

### Transforming Data

In [5]:
# Rename columns is not necessary with header=0 if we trust the source names
# But let's check what we have
print(df.columns)

Index(['Location', 'Direction', 'CorrectionFactor', 'PercentPassing20%',
       'PercentPassing10%', 'date', 'Volume'],
      dtype='object')

In [6]:
# Ensure 'date' is datetime
# Note: The column name is 'date' (lowercase) based on header=0
if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], errors='coerce', format='%Y-%m-%d')
    df = df.dropna(subset=['date'])
    df = df.set_index('date')
else:
    print("Warning: 'date' column not found!")
    # Fallback or debug print
    print(df.columns)

In [7]:
df.head()

,Location,Direction,CorrectionFactor,PercentPassing20%,PercentPassing10%,Volume
date,,,,,,
2021-01-01,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Westbound,1.106145,0.7,0.6,91.810056
2021-01-01,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Eastbound,1.106145,0.7,0.6,3.318436
2021-01-02,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Westbound,1.106145,0.7,0.6,57.519553
2021-01-02,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Eastbound,1.106145,0.7,0.6,4.424581
2021-01-03,1815 Cornwall - Northside,1815 Cornwall - Northside Cyclist Westbound,1.106145,0.7,0.6,315.251397

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 81386 entries, 2021-01-01 to 2024-09-19
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Location           81386 non-null  object
 1   Direction          81386 non-null  object
 2   CorrectionFactor   81386 non-null  float64
 3   PercentPassing20%  70200 non-null  float64
 4   PercentPassing10%  70200 non-null  float64
 5   Volume             67020 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.3+ MB

## Exploratory Analysis

### Unique Values in Column A (Location)

In [9]:
print("Counts of each unique value for Location:")
if 'Location' in df.columns:
    location_counts = df['Location'].value_counts()
    print(location_counts)
else:
    print("Column 'Location' not found.")

Counts of each unique value for Location:
Location
1815 Cornwall - Northside                          2716
1818 Cornwall - Southside                          2716
1850 York                                          2716
486 East 37th                                      2716
821 Powell                                         2716
885 Dunsmuir                                       2716
Dunsmuir at Beatty                                 2716
Hornby at Robson                                   2716
Fleming at East 57th                               2716
Helmcken at Burrard                                2716
Comox at Thurlow                                   2716
Vanness at Brant                                   2716
Seawall at Harbour Green Park                      2716
Seawall at HMCS Discovery                          2716
Union at Hawks                                     2716
Stephens at Point Grey                             2716
Seawall at David Lam Park                          2716
Seawall at Creekside Community Centre              2716
Lions Gate Bridge at Spirit Trail - Westside       2716
Lions Gate Bridge at Spirit Trail - Eastside       2716
Burrard at Cornwall - Eastside - Burrard Bridge    2632
Cambie Bridge - Eastside                           2600
Burrard at Cornwall - Westside - Burrard Bridge    2528
Central Valley Greenway at Victoria                2410
Canada Line Bridge at West Kent                    2028
Dunsmuir Viaduct at Main                           1828
Point Grey at Stephens                             1824
Seawall at Lumbermen's Arch                        1790
Seawall at Second Beach Pool                       1772
Point Grey at Alma                                 1762
East 10th at Clark                                 1760
Alex Fraser Bridge West                            1316
Point Grey at Volunteer Park                       1094
Richards at Dunsmuir                               1094
Alex Fraser Bridge East                             336
Seawall at Morton Park                              292
Name: count, dtype: int64

### Unique Values in Column B (Direction)

In [10]:
print("Counts of each unique value for Direction:")
if 'Direction' in df.columns:
    direction_counts = df['Direction'].value_counts()
    print(direction_counts)
else:
    print("Column 'Direction' not found.")

Counts of each unique value for Direction:
Direction
1815 Cornwall - Northside Cyclist Westbound    1358
1815 Cornwall - Northside Cyclist Eastbound    1358
1818 Cornwall - Southside Cyclist Eastbound    1358
1818 Cornwall - Southside Cyclist Westbound    1358
1850 York Cyclist Eastbound                    1358
                                               ...
Richards at Dunsmuir Cyclist Northbound         547
Alex Fraser Bridge East Cyclist B               168
Alex Fraser Bridge East Cyclist A               168
Seawall at Morton Park Cyclist Northbound       146
Seawall at Morton Park Cyclist Southbound       146
Name: count, Length: 72, dtype: int64

### Analysis of Column G (Volume)

In [11]:
if 'Volume' in df.columns:
    min_vol = df['Volume'].min()
    max_vol = df['Volume'].max()
    median_vol = df['Volume'].median()
    
    print(f"Minimum Volume: {min_vol}")
    print(f"Maximum Volume: {max_vol}")
    print(f"Median Volume: {median_vol}")
else:
    print("Column 'Volume' not found.")

Minimum Volume: 0.0
Maximum Volume: 25446.05
Median Volume: 308.9943820224723

### Top 5 Stations by Total Traffic (Broken - Pending Update)

In [12]:
# Commented out due to schema changes
# total_traffic = df.sum().sort_values(ascending=False).head(5)
# total_traffic.plot(kind='bar', color='skyblue')
# plt.title('Top 5 Stations by Total Bicycle Traffic')
# plt.ylabel('Total Traffic Count')
# plt.xlabel('Station')
# plt.show()

### Burrard Bridge Traffic Trends (Broken - Pending Update)

In [13]:
# Commented out due to schema changes
# burrard = "Burrard at Cornwall - Eastside - Burrard Bridge"
# df[burrard].plot(kind='line', color='orange')
# plt.title('Burrard Bridge Traffic Trends')
# plt.ylabel('Bicycle Traffic Count')
# plt.xlabel('Date')
# plt.show()